title: Pia Smith Resume and Portfolio
author: Pia Smith
email: theequationofacircle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Python Developer with Eye for Design  
  and a Love of Databases

# social links
twitter_username: PeayahWerner
github_username:  peayah

show_excerpts: true # set to false to remove excerpts on the homepage

# collections
collections: 
  observations:
    sort_by: date
    output: true
   portfolio-pieces:
    output: true

# build
theme: minima
