title: Pia Smith Resume and Portfolio
author: Pia Smith
email: theequationofacircle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Django Python Developer with Eye for Design  
  and a Love of Databases

# social links
github_username:  peayah

show_excerpts: true # set to false to remove excerpts on the homepage

baseurl: /

# collections
collections:
  posts:
    output: true
    permalink: posts/:title
  
  web_portfolio:
    output: true
    permalink: none
    
  web_projects:
    output: true
    
  web_posts:
    output: true

  code-samles:
    output: true
    permalink: /code-samples/:path/    
    
# build
theme: minima
