title: Pia Smith Resume and Portfolio
author: Pia Smith
email: theequationofacircle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Python Developer with Eye for Design  
  and a Love of Databases

# social links
twitter_username: PeayahWerner
github_username:  peayah

show_excerpts: true # set to false to remove excerpts on the homepage

baseurl: /

# collections
collections:
  output: true
  portfolio-pieces:   
  order:
    - maze-finder.md
    - wordpress-sites.md
    - portfolio-site.md 
  # observations:
    # sort_by: date
  code-samles:
    output: true
    permalink: /code-samples/:path/
    
# build
theme: minima
