title: Pia Smith Portfolio
author: Pia Smith
email: theequationofacircle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Python Developer with Eye for Design<br/>
  and a Love of Databases

# social links
twitter_username: pia_smith
github_username:  peayah

show_excerpts: true # set to false to remove excerpts on the homepage

# build
theme: minima
