title: Awesomeness
author: P
theme: minima
email: p@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Best blog ever

# social links
twitter_username: p
github_username:  p

show_excerpts: true # set to false to remove excerpts on the homepage
